use tauri::{
    plugin::{PluginHandle, PluginApi},
    AppHandle, Runtime,
};

use crate::{
    error::Result,
    models::{
        EmbeddingInput, EmbeddingOutput, InferenceInput, InferenceOutput, LoadModelOptions,
        ModelInfo,
    },
};

// The Kotlin plugin is registered under this identifier.
#[cfg(target_os = "android")]
const PLUGIN_IDENTIFIER: &str = "com.plugin.litert";

// iOS: no Swift package is included yet. The binding macro below compiles but
// the Swift implementation must be added via `tauri plugin ios add` before
// iOS builds will work at runtime.
#[cfg(target_os = "ios")]
const PLUGIN_IDENTIFIER: &str = "LiteRtPlugin";

pub fn init<R: Runtime, C: serde::de::DeserializeOwned>(
    _app: &AppHandle<R>,
    api: &PluginApi<R, C>,
) -> Result<LiteRt<R>> {
    #[cfg(target_os = "android")]
    let handle = api
        .register_android_plugin(PLUGIN_IDENTIFIER, "LiteRtPlugin")
        .map_err(|e| crate::error::Error::Backend(e.to_string()))?;

    #[cfg(target_os = "ios")]
    let handle = api
        .register_ios_plugin(init_plugin_litert)
        .map_err(|e| crate::error::Error::Backend(e.to_string()))?;

    Ok(LiteRt(handle))
}

/// Mobile plugin handle – thin wrapper that delegates every call to the
/// native Kotlin / Swift implementation via Tauri's mobile IPC bridge.
pub struct LiteRt<R: Runtime>(PluginHandle<R>);

impl<R: Runtime> LiteRt<R> {
    pub fn load_model(&self, opts: LoadModelOptions) -> Result<ModelInfo> {
        self.0
            .run_mobile_plugin("loadModel", opts)
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn unload_model(&self, model_id: &str) -> Result<()> {
        self.0
            .run_mobile_plugin("unloadModel", serde_json::json!({ "modelId": model_id }))
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn list_models(&self) -> Result<Vec<ModelInfo>> {
        // Kotlin resolves with { "models": [...] }; unwrap the wrapper.
        #[derive(serde::Deserialize)]
        struct ListModelsResponse {
            models: Vec<ModelInfo>,
        }
        self.0
            .run_mobile_plugin::<ListModelsResponse>("listModels", ())
            .map(|r| r.models)
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn get_model_info(&self, model_id: &str) -> Result<ModelInfo> {
        self.0
            .run_mobile_plugin("getModelInfo", serde_json::json!({ "modelId": model_id }))
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn run_inference(&self, input: InferenceInput) -> Result<InferenceOutput> {
        self.0
            .run_mobile_plugin("runInference", input)
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn create_embedding(&self, input: EmbeddingInput) -> Result<EmbeddingOutput> {
        self.0
            .run_mobile_plugin("createEmbedding", input)
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn tts_speak(&self, text: String, rate: f32, pitch: f32) -> Result<()> {
        self.0
            .run_mobile_plugin::<()>("ttsSpeak", serde_json::json!({ "text": text, "rate": rate, "pitch": pitch }))
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    pub fn tts_cancel(&self) -> Result<()> {
        self.0
            .run_mobile_plugin::<()>("ttsCancel", ())
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    /// Copy any APK assets under `assets/bundled-models/` into `target_dir`
    /// (skipping files that already exist there). Returns the number copied.
    /// `target_dir` should be the app's `models/` directory so the result is
    /// immediately visible to `get_model_path`.
    pub fn extract_bundled_models(&self, target_dir: &str) -> Result<u32> {
        #[derive(serde::Deserialize)]
        struct ExtractResponse {
            copied: u32,
        }
        self.0
            .run_mobile_plugin::<ExtractResponse>(
                "extractBundledModels",
                serde_json::json!({ "targetDir": target_dir }),
            )
            .map(|r| r.copied)
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }

    /// Query the best available LLM accelerator using the SDK's built-in
    /// NpuCompatibilityChecker (checks Qualcomm/MediaTek/Google Tensor SoC
    /// lists at runtime). Returns "npu", "gpu", or "cpu".
    pub fn query_accelerator_support(&self) -> Result<crate::AcceleratorSupport> {
        self.0
            .run_mobile_plugin::<crate::AcceleratorSupport>("queryAcceleratorSupport", ())
            .map_err(|e| crate::error::Error::Backend(e.to_string()))
    }
}

// iOS Swift package entry-point (generated by `tauri plugin ios add`).
#[cfg(target_os = "ios")]
tauri::ios_plugin_binding!(init_plugin_litert);
